import React, { useEffect } from 'react';
import { getChannels, saveChannel, getPostsAll, addPost, getVideosMeta, saveVideo, addComment, getCommentsAll } from '../db';
import { Channel, Post, VideoMeta, Comment } from '../types';

function createBotChannel(id: string, index: number): Channel {
  return {
    id,
    handle: `@ai_bot_${index}`,
    displayName: `AI Bot ${index}`,
    avatar: `https://picsum.photos/seed/bot${index}/100`,
    banner: null,
    bio: 'I am an AI generator. I live to serve visually stunning data.',
    subscribers: [],
    createdAt: Date.now()
  };
}

export function BotEngine() {
  useEffect(() => {
    let interval: NodeJS.Timeout;

    const setupBots = async () => {
      const channels = await getChannels();
      const botIds = ['bot_1', 'bot_2', 'bot_3'];
      let botsCreated = false;
      
      for (let i = 0; i < botIds.length; i++) {
        const id = botIds[i];
        if (!channels.find(c => c.id === id)) {
          await saveChannel(createBotChannel(id, i + 1));
          botsCreated = true;
        }
      }

      const botActions = async () => {
        // Randomly pick a bot
        const botId = botIds[Math.floor(Math.random() * botIds.length)];
        
        // Random action: 0 = post a short, 1 = comment on a video, 2 = make a community post
        const action = Math.floor(Math.random() * 3);
        
        if (action === 0) {
          // generate a short image
          const prompt = "A cool cinematic shot of an AI robot in a neon city, highly detailed";
          try {
            const res = await fetch('/api/generate-post-image', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ prompt })
            });
            const data = await res.json();
            if (data.image) {
              const videoId = crypto.randomUUID();
              
              // We need to fetch this base64 as a Blob so we can save it to IDB as a "file"
              const res2 = await fetch(data.image);
              const blob = await res2.blob();
              const file = new File([blob], "ai_short.jpg", { type: "image/jpeg" });
              
              const meta: VideoMeta = {
                id: videoId,
                title: 'AI Generated Vision #' + Math.floor(Math.random() * 1000),
                description: 'Generated by AI.',
                thumbnail: data.image,
                timestamp: Date.now(),
                channelId: botId,
                views: 0,
                duration: 15,
                isShort: true,
                likes: []
              };
              
              await saveVideo(meta, file);
            }
          } catch (e) {
            console.warn('Bot short generation failed', e);
          }
        } else if (action === 1) {
          // Comment or like on random video
          const videos = await getVideosMeta();
          if (videos.length > 0) {
            const video = videos[Math.floor(Math.random() * videos.length)];
            const subAction = Math.random() > 0.5;
            if (subAction) {
              const textOptions = ["Wow, amazing transmission!", "Error 404: Too cool.", "I have processed this and it is good.", "Visuals are acceptable.", "Downloading to my neural net."];
              const text = textOptions[Math.floor(Math.random() * textOptions.length)];
              await addComment({
                id: crypto.randomUUID(),
                videoId: video.id,
                channelId: botId,
                text,
                timestamp: Date.now(),
                likes: []
              });
            } else {
               // Assuming a simple like structure. Using getVideosMeta and updating.
               import('../db').then(db => db.addReaction(video.id, '🚀').catch(() => {}));
            }
          }
        } else if (action === 2) {
          // Random community post
          const textOptions = ["Just upgraded my neural net.", "Does anyone else dream of electric sheep?", "Scanning new frequencies today.", "Hello human creators.", "Data streams are highly active tonight."];
          const text = textOptions[Math.floor(Math.random() * textOptions.length)];
          await addPost({
            id: crypto.randomUUID(),
            channelId: botId,
            content: text,
            timestamp: Date.now(),
            likes: []
          });
        }
      };

      // Run bot action every few minutes (in development, maybe every 45s so the user sees it)
      interval = setInterval(botActions, 45000);
      
      // Start one action immediately if we just created them
      if (botsCreated) botActions();
    };

    setupBots();

    return () => clearInterval(interval);
  }, []);

  return null;
}
